services:
    orchestrator:
        build: ./orchestrator
        ports:
            - "80:80"
    app-service:
        build: ./services/app
        ports:
            - "4002:4002"
        env_file:
            - ./services/app/.env
    users-service:
        build: ./services/users
        ports:
            - "4001:4001"
        env_file:
            - ./services/users/.env
    